// Code generated by Kitex v0.15.2. DO NOT EDIT.

package adservice

import (
	advertise "advertiseproject/kitex_gen/advertiseproject/advertise"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetAd": kitex.NewMethodInfo(
		getAdHandler,
		newAdServiceGetAdArgs,
		newAdServiceGetAdResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AddAd": kitex.NewMethodInfo(
		addAdHandler,
		newAdServiceAddAdArgs,
		newAdServiceAddAdResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteAd": kitex.NewMethodInfo(
		deleteAdHandler,
		newAdServiceDeleteAdArgs,
		newAdServiceDeleteAdResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateAd": kitex.NewMethodInfo(
		updateAdHandler,
		newAdServiceUpdateAdArgs,
		newAdServiceUpdateAdResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	adServiceServiceInfo                = NewServiceInfo()
	adServiceServiceInfoForClient       = NewServiceInfoForClient()
	adServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return adServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return adServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return adServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AdService"
	handlerType := (*advertise.AdService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "advertise",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func getAdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advertise.AdServiceGetAdArgs)
	realResult := result.(*advertise.AdServiceGetAdResult)
	success, err := handler.(advertise.AdService).GetAd(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdServiceGetAdArgs() interface{} {
	return advertise.NewAdServiceGetAdArgs()
}

func newAdServiceGetAdResult() interface{} {
	return advertise.NewAdServiceGetAdResult()
}

func addAdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advertise.AdServiceAddAdArgs)
	realResult := result.(*advertise.AdServiceAddAdResult)
	success, err := handler.(advertise.AdService).AddAd(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdServiceAddAdArgs() interface{} {
	return advertise.NewAdServiceAddAdArgs()
}

func newAdServiceAddAdResult() interface{} {
	return advertise.NewAdServiceAddAdResult()
}

func deleteAdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advertise.AdServiceDeleteAdArgs)
	realResult := result.(*advertise.AdServiceDeleteAdResult)
	success, err := handler.(advertise.AdService).DeleteAd(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdServiceDeleteAdArgs() interface{} {
	return advertise.NewAdServiceDeleteAdArgs()
}

func newAdServiceDeleteAdResult() interface{} {
	return advertise.NewAdServiceDeleteAdResult()
}

func updateAdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advertise.AdServiceUpdateAdArgs)
	realResult := result.(*advertise.AdServiceUpdateAdResult)
	success, err := handler.(advertise.AdService).UpdateAd(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdServiceUpdateAdArgs() interface{} {
	return advertise.NewAdServiceUpdateAdArgs()
}

func newAdServiceUpdateAdResult() interface{} {
	return advertise.NewAdServiceUpdateAdResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetAd(ctx context.Context, req *advertise.GetAdReq) (r *advertise.GetAdRes, err error) {
	var _args advertise.AdServiceGetAdArgs
	_args.Req = req
	var _result advertise.AdServiceGetAdResult
	if err = p.c.Call(ctx, "GetAd", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddAd(ctx context.Context, req *advertise.AddAdReq) (r *advertise.AddAdRes, err error) {
	var _args advertise.AdServiceAddAdArgs
	_args.Req = req
	var _result advertise.AdServiceAddAdResult
	if err = p.c.Call(ctx, "AddAd", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteAd(ctx context.Context, req *advertise.DeleteAdReq) (r *advertise.DeleteAdRes, err error) {
	var _args advertise.AdServiceDeleteAdArgs
	_args.Req = req
	var _result advertise.AdServiceDeleteAdResult
	if err = p.c.Call(ctx, "DeleteAd", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateAd(ctx context.Context, req *advertise.UpdateAdReq) (r *advertise.UpdateAdRes, err error) {
	var _args advertise.AdServiceUpdateAdArgs
	_args.Req = req
	var _result advertise.AdServiceUpdateAdResult
	if err = p.c.Call(ctx, "UpdateAd", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
