// Code generated by Kitex v0.15.2. DO NOT EDIT.

package adservice

import (
	advertise "advertiseproject/kitex_gen/advertiseproject/advertise"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetAd(ctx context.Context, req *advertise.GetAdReq, callOptions ...callopt.Option) (r *advertise.GetAdRes, err error)
	AddAd(ctx context.Context, req *advertise.AddAdReq, callOptions ...callopt.Option) (r *advertise.AddAdRes, err error)
	DeleteAd(ctx context.Context, req *advertise.DeleteAdReq, callOptions ...callopt.Option) (r *advertise.DeleteAdRes, err error)
	UpdateAd(ctx context.Context, req *advertise.UpdateAdReq, callOptions ...callopt.Option) (r *advertise.UpdateAdRes, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAdServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAdServiceClient struct {
	*kClient
}

func (p *kAdServiceClient) GetAd(ctx context.Context, req *advertise.GetAdReq, callOptions ...callopt.Option) (r *advertise.GetAdRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAd(ctx, req)
}

func (p *kAdServiceClient) AddAd(ctx context.Context, req *advertise.AddAdReq, callOptions ...callopt.Option) (r *advertise.AddAdRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddAd(ctx, req)
}

func (p *kAdServiceClient) DeleteAd(ctx context.Context, req *advertise.DeleteAdReq, callOptions ...callopt.Option) (r *advertise.DeleteAdRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteAd(ctx, req)
}

func (p *kAdServiceClient) UpdateAd(ctx context.Context, req *advertise.UpdateAdReq, callOptions ...callopt.Option) (r *advertise.UpdateAdRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateAd(ctx, req)
}
