// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package base

import (
	"fmt"
)

type BaseRes struct {
	Code int64  `thrift:"code,1" frugal:"1,default,i64" json:"code"`
	Msg  string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewBaseRes() *BaseRes {
	return &BaseRes{}
}

func (p *BaseRes) InitDefault() {
}

func (p *BaseRes) GetCode() (v int64) {
	return p.Code
}

func (p *BaseRes) GetMsg() (v string) {
	return p.Msg
}
func (p *BaseRes) SetCode(val int64) {
	p.Code = val
}
func (p *BaseRes) SetMsg(val string) {
	p.Msg = val
}

func (p *BaseRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseRes(%+v)", *p)
}

var fieldIDToName_BaseRes = map[int16]string{
	1: "code",
	2: "msg",
}
