// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package advertise

import (
	"advertiseproject/kitex_gen/base"
	"context"
	"fmt"
)

type Advertise struct {
	Id          int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Description string `thrift:"description,2" frugal:"2,default,string" json:"description"`
	Name        string `thrift:"name,3" frugal:"3,default,string" json:"name"`
	Stock       int64  `thrift:"stock,4" frugal:"4,default,i64" json:"stock"`
}

func NewAdvertise() *Advertise {
	return &Advertise{}
}

func (p *Advertise) InitDefault() {
}

func (p *Advertise) GetId() (v int64) {
	return p.Id
}

func (p *Advertise) GetDescription() (v string) {
	return p.Description
}

func (p *Advertise) GetName() (v string) {
	return p.Name
}

func (p *Advertise) GetStock() (v int64) {
	return p.Stock
}
func (p *Advertise) SetId(val int64) {
	p.Id = val
}
func (p *Advertise) SetDescription(val string) {
	p.Description = val
}
func (p *Advertise) SetName(val string) {
	p.Name = val
}
func (p *Advertise) SetStock(val int64) {
	p.Stock = val
}

func (p *Advertise) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Advertise(%+v)", *p)
}

var fieldIDToName_Advertise = map[int16]string{
	1: "id",
	2: "description",
	3: "name",
	4: "stock",
}

type GetAdReq struct {
	Id   int64  `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	Name string `thrift:"name,2" frugal:"2,default,string" json:"name"`
}

func NewGetAdReq() *GetAdReq {
	return &GetAdReq{}
}

func (p *GetAdReq) InitDefault() {
}

func (p *GetAdReq) GetId() (v int64) {
	return p.Id
}

func (p *GetAdReq) GetName() (v string) {
	return p.Name
}
func (p *GetAdReq) SetId(val int64) {
	p.Id = val
}
func (p *GetAdReq) SetName(val string) {
	p.Name = val
}

func (p *GetAdReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAdReq(%+v)", *p)
}

var fieldIDToName_GetAdReq = map[int16]string{
	1: "id",
	2: "name",
}

type GetAdRes struct {
	Ad      *Advertise    `thrift:"ad,1" frugal:"1,default,Advertise" json:"ad"`
	BaseRes *base.BaseRes `thrift:"baseRes,255" frugal:"255,default,base.BaseRes" json:"baseRes"`
}

func NewGetAdRes() *GetAdRes {
	return &GetAdRes{}
}

func (p *GetAdRes) InitDefault() {
}

var GetAdRes_Ad_DEFAULT *Advertise

func (p *GetAdRes) GetAd() (v *Advertise) {
	if !p.IsSetAd() {
		return GetAdRes_Ad_DEFAULT
	}
	return p.Ad
}

var GetAdRes_BaseRes_DEFAULT *base.BaseRes

func (p *GetAdRes) GetBaseRes() (v *base.BaseRes) {
	if !p.IsSetBaseRes() {
		return GetAdRes_BaseRes_DEFAULT
	}
	return p.BaseRes
}
func (p *GetAdRes) SetAd(val *Advertise) {
	p.Ad = val
}
func (p *GetAdRes) SetBaseRes(val *base.BaseRes) {
	p.BaseRes = val
}

func (p *GetAdRes) IsSetAd() bool {
	return p.Ad != nil
}

func (p *GetAdRes) IsSetBaseRes() bool {
	return p.BaseRes != nil
}

func (p *GetAdRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAdRes(%+v)", *p)
}

var fieldIDToName_GetAdRes = map[int16]string{
	1:   "ad",
	255: "baseRes",
}

type AddAdReq struct {
	Ad *Advertise `thrift:"ad,1" frugal:"1,default,Advertise" json:"ad"`
}

func NewAddAdReq() *AddAdReq {
	return &AddAdReq{}
}

func (p *AddAdReq) InitDefault() {
}

var AddAdReq_Ad_DEFAULT *Advertise

func (p *AddAdReq) GetAd() (v *Advertise) {
	if !p.IsSetAd() {
		return AddAdReq_Ad_DEFAULT
	}
	return p.Ad
}
func (p *AddAdReq) SetAd(val *Advertise) {
	p.Ad = val
}

func (p *AddAdReq) IsSetAd() bool {
	return p.Ad != nil
}

func (p *AddAdReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddAdReq(%+v)", *p)
}

var fieldIDToName_AddAdReq = map[int16]string{
	1: "ad",
}

type AddAdRes struct {
	BaseRes *base.BaseRes `thrift:"baseRes,255" frugal:"255,default,base.BaseRes" json:"baseRes"`
}

func NewAddAdRes() *AddAdRes {
	return &AddAdRes{}
}

func (p *AddAdRes) InitDefault() {
}

var AddAdRes_BaseRes_DEFAULT *base.BaseRes

func (p *AddAdRes) GetBaseRes() (v *base.BaseRes) {
	if !p.IsSetBaseRes() {
		return AddAdRes_BaseRes_DEFAULT
	}
	return p.BaseRes
}
func (p *AddAdRes) SetBaseRes(val *base.BaseRes) {
	p.BaseRes = val
}

func (p *AddAdRes) IsSetBaseRes() bool {
	return p.BaseRes != nil
}

func (p *AddAdRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddAdRes(%+v)", *p)
}

var fieldIDToName_AddAdRes = map[int16]string{
	255: "baseRes",
}

type DeleteAdReq struct {
	Id   int64  `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	Name string `thrift:"name,2" frugal:"2,default,string" json:"name"`
}

func NewDeleteAdReq() *DeleteAdReq {
	return &DeleteAdReq{}
}

func (p *DeleteAdReq) InitDefault() {
}

func (p *DeleteAdReq) GetId() (v int64) {
	return p.Id
}

func (p *DeleteAdReq) GetName() (v string) {
	return p.Name
}
func (p *DeleteAdReq) SetId(val int64) {
	p.Id = val
}
func (p *DeleteAdReq) SetName(val string) {
	p.Name = val
}

func (p *DeleteAdReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteAdReq(%+v)", *p)
}

var fieldIDToName_DeleteAdReq = map[int16]string{
	1: "id",
	2: "name",
}

type DeleteAdRes struct {
	Res *base.BaseRes `thrift:"res,255" frugal:"255,default,base.BaseRes" json:"res"`
}

func NewDeleteAdRes() *DeleteAdRes {
	return &DeleteAdRes{}
}

func (p *DeleteAdRes) InitDefault() {
}

var DeleteAdRes_Res_DEFAULT *base.BaseRes

func (p *DeleteAdRes) GetRes() (v *base.BaseRes) {
	if !p.IsSetRes() {
		return DeleteAdRes_Res_DEFAULT
	}
	return p.Res
}
func (p *DeleteAdRes) SetRes(val *base.BaseRes) {
	p.Res = val
}

func (p *DeleteAdRes) IsSetRes() bool {
	return p.Res != nil
}

func (p *DeleteAdRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteAdRes(%+v)", *p)
}

var fieldIDToName_DeleteAdRes = map[int16]string{
	255: "res",
}

type UpdateAdReq struct {
	Ad *Advertise `thrift:"ad,1" frugal:"1,default,Advertise" json:"ad"`
}

func NewUpdateAdReq() *UpdateAdReq {
	return &UpdateAdReq{}
}

func (p *UpdateAdReq) InitDefault() {
}

var UpdateAdReq_Ad_DEFAULT *Advertise

func (p *UpdateAdReq) GetAd() (v *Advertise) {
	if !p.IsSetAd() {
		return UpdateAdReq_Ad_DEFAULT
	}
	return p.Ad
}
func (p *UpdateAdReq) SetAd(val *Advertise) {
	p.Ad = val
}

func (p *UpdateAdReq) IsSetAd() bool {
	return p.Ad != nil
}

func (p *UpdateAdReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateAdReq(%+v)", *p)
}

var fieldIDToName_UpdateAdReq = map[int16]string{
	1: "ad",
}

type UpdateAdRes struct {
	Res *base.BaseRes `thrift:"res,255" frugal:"255,default,base.BaseRes" json:"res"`
}

func NewUpdateAdRes() *UpdateAdRes {
	return &UpdateAdRes{}
}

func (p *UpdateAdRes) InitDefault() {
}

var UpdateAdRes_Res_DEFAULT *base.BaseRes

func (p *UpdateAdRes) GetRes() (v *base.BaseRes) {
	if !p.IsSetRes() {
		return UpdateAdRes_Res_DEFAULT
	}
	return p.Res
}
func (p *UpdateAdRes) SetRes(val *base.BaseRes) {
	p.Res = val
}

func (p *UpdateAdRes) IsSetRes() bool {
	return p.Res != nil
}

func (p *UpdateAdRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateAdRes(%+v)", *p)
}

var fieldIDToName_UpdateAdRes = map[int16]string{
	255: "res",
}

type AdService interface {
	GetAd(ctx context.Context, req *GetAdReq) (r *GetAdRes, err error)

	AddAd(ctx context.Context, req *AddAdReq) (r *AddAdRes, err error)

	DeleteAd(ctx context.Context, req *DeleteAdReq) (r *DeleteAdRes, err error)

	UpdateAd(ctx context.Context, req *UpdateAdReq) (r *UpdateAdRes, err error)
}

type AdServiceGetAdArgs struct {
	Req *GetAdReq `thrift:"req,1" frugal:"1,default,GetAdReq" json:"req"`
}

func NewAdServiceGetAdArgs() *AdServiceGetAdArgs {
	return &AdServiceGetAdArgs{}
}

func (p *AdServiceGetAdArgs) InitDefault() {
}

var AdServiceGetAdArgs_Req_DEFAULT *GetAdReq

func (p *AdServiceGetAdArgs) GetReq() (v *GetAdReq) {
	if !p.IsSetReq() {
		return AdServiceGetAdArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdServiceGetAdArgs) SetReq(val *GetAdReq) {
	p.Req = val
}

func (p *AdServiceGetAdArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdServiceGetAdArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdServiceGetAdArgs(%+v)", *p)
}

var fieldIDToName_AdServiceGetAdArgs = map[int16]string{
	1: "req",
}

type AdServiceGetAdResult struct {
	Success *GetAdRes `thrift:"success,0,optional" frugal:"0,optional,GetAdRes" json:"success,omitempty"`
}

func NewAdServiceGetAdResult() *AdServiceGetAdResult {
	return &AdServiceGetAdResult{}
}

func (p *AdServiceGetAdResult) InitDefault() {
}

var AdServiceGetAdResult_Success_DEFAULT *GetAdRes

func (p *AdServiceGetAdResult) GetSuccess() (v *GetAdRes) {
	if !p.IsSetSuccess() {
		return AdServiceGetAdResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdServiceGetAdResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetAdRes)
}

func (p *AdServiceGetAdResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdServiceGetAdResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdServiceGetAdResult(%+v)", *p)
}

var fieldIDToName_AdServiceGetAdResult = map[int16]string{
	0: "success",
}

type AdServiceAddAdArgs struct {
	Req *AddAdReq `thrift:"req,1" frugal:"1,default,AddAdReq" json:"req"`
}

func NewAdServiceAddAdArgs() *AdServiceAddAdArgs {
	return &AdServiceAddAdArgs{}
}

func (p *AdServiceAddAdArgs) InitDefault() {
}

var AdServiceAddAdArgs_Req_DEFAULT *AddAdReq

func (p *AdServiceAddAdArgs) GetReq() (v *AddAdReq) {
	if !p.IsSetReq() {
		return AdServiceAddAdArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdServiceAddAdArgs) SetReq(val *AddAdReq) {
	p.Req = val
}

func (p *AdServiceAddAdArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdServiceAddAdArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdServiceAddAdArgs(%+v)", *p)
}

var fieldIDToName_AdServiceAddAdArgs = map[int16]string{
	1: "req",
}

type AdServiceAddAdResult struct {
	Success *AddAdRes `thrift:"success,0,optional" frugal:"0,optional,AddAdRes" json:"success,omitempty"`
}

func NewAdServiceAddAdResult() *AdServiceAddAdResult {
	return &AdServiceAddAdResult{}
}

func (p *AdServiceAddAdResult) InitDefault() {
}

var AdServiceAddAdResult_Success_DEFAULT *AddAdRes

func (p *AdServiceAddAdResult) GetSuccess() (v *AddAdRes) {
	if !p.IsSetSuccess() {
		return AdServiceAddAdResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdServiceAddAdResult) SetSuccess(x interface{}) {
	p.Success = x.(*AddAdRes)
}

func (p *AdServiceAddAdResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdServiceAddAdResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdServiceAddAdResult(%+v)", *p)
}

var fieldIDToName_AdServiceAddAdResult = map[int16]string{
	0: "success",
}

type AdServiceDeleteAdArgs struct {
	Req *DeleteAdReq `thrift:"req,1" frugal:"1,default,DeleteAdReq" json:"req"`
}

func NewAdServiceDeleteAdArgs() *AdServiceDeleteAdArgs {
	return &AdServiceDeleteAdArgs{}
}

func (p *AdServiceDeleteAdArgs) InitDefault() {
}

var AdServiceDeleteAdArgs_Req_DEFAULT *DeleteAdReq

func (p *AdServiceDeleteAdArgs) GetReq() (v *DeleteAdReq) {
	if !p.IsSetReq() {
		return AdServiceDeleteAdArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdServiceDeleteAdArgs) SetReq(val *DeleteAdReq) {
	p.Req = val
}

func (p *AdServiceDeleteAdArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdServiceDeleteAdArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdServiceDeleteAdArgs(%+v)", *p)
}

var fieldIDToName_AdServiceDeleteAdArgs = map[int16]string{
	1: "req",
}

type AdServiceDeleteAdResult struct {
	Success *DeleteAdRes `thrift:"success,0,optional" frugal:"0,optional,DeleteAdRes" json:"success,omitempty"`
}

func NewAdServiceDeleteAdResult() *AdServiceDeleteAdResult {
	return &AdServiceDeleteAdResult{}
}

func (p *AdServiceDeleteAdResult) InitDefault() {
}

var AdServiceDeleteAdResult_Success_DEFAULT *DeleteAdRes

func (p *AdServiceDeleteAdResult) GetSuccess() (v *DeleteAdRes) {
	if !p.IsSetSuccess() {
		return AdServiceDeleteAdResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdServiceDeleteAdResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteAdRes)
}

func (p *AdServiceDeleteAdResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdServiceDeleteAdResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdServiceDeleteAdResult(%+v)", *p)
}

var fieldIDToName_AdServiceDeleteAdResult = map[int16]string{
	0: "success",
}

type AdServiceUpdateAdArgs struct {
	Req *UpdateAdReq `thrift:"req,1" frugal:"1,default,UpdateAdReq" json:"req"`
}

func NewAdServiceUpdateAdArgs() *AdServiceUpdateAdArgs {
	return &AdServiceUpdateAdArgs{}
}

func (p *AdServiceUpdateAdArgs) InitDefault() {
}

var AdServiceUpdateAdArgs_Req_DEFAULT *UpdateAdReq

func (p *AdServiceUpdateAdArgs) GetReq() (v *UpdateAdReq) {
	if !p.IsSetReq() {
		return AdServiceUpdateAdArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdServiceUpdateAdArgs) SetReq(val *UpdateAdReq) {
	p.Req = val
}

func (p *AdServiceUpdateAdArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdServiceUpdateAdArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdServiceUpdateAdArgs(%+v)", *p)
}

var fieldIDToName_AdServiceUpdateAdArgs = map[int16]string{
	1: "req",
}

type AdServiceUpdateAdResult struct {
	Success *UpdateAdRes `thrift:"success,0,optional" frugal:"0,optional,UpdateAdRes" json:"success,omitempty"`
}

func NewAdServiceUpdateAdResult() *AdServiceUpdateAdResult {
	return &AdServiceUpdateAdResult{}
}

func (p *AdServiceUpdateAdResult) InitDefault() {
}

var AdServiceUpdateAdResult_Success_DEFAULT *UpdateAdRes

func (p *AdServiceUpdateAdResult) GetSuccess() (v *UpdateAdRes) {
	if !p.IsSetSuccess() {
		return AdServiceUpdateAdResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdServiceUpdateAdResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateAdRes)
}

func (p *AdServiceUpdateAdResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdServiceUpdateAdResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdServiceUpdateAdResult(%+v)", *p)
}

var fieldIDToName_AdServiceUpdateAdResult = map[int16]string{
	0: "success",
}
